default_hour: 9
default_minute: 0
editor: vim
encrypt: false
highlight: true
journals:
  code:    /mnt/Data/Documents/Journal/code.jrnl
  idea:    /mnt/Data/Documents/Journal/idea.jrnl
  til:     /mnt/Data/Documents/Journal/til.jrnl
  work:    /mnt/Data/Documents/Journal/work.jrnl
  default: /mnt/Data/Documents/Journal/life.jrnl
linewrap: 79
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: 2.0.0-rc1
