default_hour: 9
default_minute: 0
editor: vim
encrypt: false
highlight: true
journals:
  test: /home/robin/Downloads/hekko.jrnl
linewrap: 79
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: 2.0.0-rc1
